name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
        - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
        - '*.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Docker
      run: docker build . --file Dockerfile
